### PR TITLE
feat(cli): add template commands

### PR DESCRIPTION
**Pull request by march26bot**
## Summary
- add `vmsmith template create`, `list`, and `delete` commands wired into the root CLI
- cover the local template CRUD flow in `internal/cli/commands_test.go`
- mark roadmap item 2.4.4 complete

## Testing
- not run in this environment (`go`/`gofmt` toolchain unavailable in the runner)

### CODE REVIEW

**Review by chinmay28 — CHANGES_REQUESTED** [review]
Thanks for wiring up the CLI commands — the overall shape matches the other CLI subcommands and the roadmap item. However, there is a blocking bug that makes `template create` fail at runtime despite the new test passing.

## Blocking issue — `template create` stores with an empty key

`templateCreateCmd` in `internal/cli/template.go` constructs a `types.VMTemplate` without setting `ID`, `CreatedAt`, or `UpdatedAt`:

```go
tpl, err := mgr.CreateTemplate(&types.VMTemplate{
    Name:        name,
    Image:       strings.TrimSpace(image),
    ...
    // no ID, no CreatedAt, no UpdatedAt
})
```

Unlike `CreateImage` (which generates `img-<unix-nano>` and sets `CreatedAt` inside the manager), `storage.Manager.CreateTemplate` just forwards straight to `store.PutTemplate` (see `internal/storage/image.go:71-76`). `PutTemplate` uses `tpl.ID` as the bbolt key, and bbolt rejects empty keys with `"key required"`.

I reproduced this locally on this branch:

```
$ go test ./internal/cli/ -run TestCLI_TemplateCreate_List_Delete -v
=== RUN   TestCLI_TemplateCreate_List_Delete
    commands_test.go:950: template create: key required
--- FAIL: TestCLI_TemplateCreate_List_Delete (0.03s)
FAIL
```

The fix should either:
1. Populate `ID`, `CreatedAt`, `UpdatedAt` in the CLI (mirror `handlers_template.go:26-42`), or
2. Better: move the ID/timestamp generation into `storage.Manager.CreateTemplate` so both the API and CLI paths share the same logic. If you go this route, the API handler's `toTemplate(now)` can be simplified too.

## Test does not actually catch the bug

The test appears to pass in CI but the assertions are too loose to catch the empty-ID store path:

- `if !strings.Contains(deleteOut, stored.ID)` — `stored.ID` is `""`, and every string contains the empty substring, so this check never fails.
- The sort-by-`CreatedAt` path is never exercised because only one template is created with a zero timestamp.

Please tighten the assertions after fixing the ID generation, e.g. `if !strings.HasPrefix(stored.ID, "tmpl-")` and verify the delete output literally contains the generated ID.

## Validation inconsistency with the API

The API (`validation.go:167-188`) enforces:
- Name must match `vmNameRe` (1-64 chars, alphanumeric/hyphen).
- CPUs ∈ [1, 128], RAM_MB ∈ [128, 1048576], Disk_GB ∈ [1, 10240].
- Tags normalized via `normalizeTags` (lowercase, 1-32 chars, specific charset).

The CLI only checks non-empty name/image, and uses `normalizeTagsForCLI` which silently drops empty tags rather than rejecting them. Since the CLI writes directly to the store, this means a CLI-created template can be stored with values that the API would reject — and those records will then be listed/served via the API. Please call the API validators (at minimum `validateTemplateRequest`-equivalent checks and `normalizeTags`) so the two paths can't diverge.

## Minor

- `templateCreateCmd.MarkFlagRequired("image")` discards the error. Consider handling it in the `init()` to surface any bad wiring (matches idiomatic Cobra usage).
- The "Networks: %d attached" line hides the real configuration. For parity with `vm create` output it would be nicer to list the host interfaces.

Once the ID generation is fixed and the test genuinely validates the behavior, this looks good to land. The rest of the structure (registration in `root.go`, storage manager reuse, pagination, help text) is solid.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by chinmay28 — CHANGES_REQUESTED** [review]
Nice work on roadmap item 2.4.4. The shape of the feature is good — refactoring shared validation into `internal/validate` and moving ID/timestamp generation into `storage.Manager.CreateTemplate` keeps the CLI and API paths in sync. Build, `go vet`, and `gofmt` are all clean; `TestCLI_TemplateCreate_List_Delete` and `TestCLI_TemplateList_PaginatesByCreationTime` pass.

However, `TestCLI_TemplateCreate_RejectsInvalidInput` is broken by a subtest state leak and will fail CI:

```
--- FAIL: TestCLI_TemplateCreate_RejectsInvalidInput/duplicate_name
    commands_test.go:1089: error code = "invalid_spec", want "invalid_name"
```

Root cause: the `empty_tag` subtest passes `--tag " "` and `--tag prod`. The `resetAllFlags` helper (pre-existing) calls `f.Value.Set("")` on `stringSlice` flags *before* clearing `Changed`, so pflag's stringSlice appends rather than replaces, and the `" "` value leaks into the next subtest. When the `duplicate_name` subtest runs, `NormalizeTags` sees the leaked empty value and returns `invalid_spec` before `ValidateUniqueTemplateName` ever runs.

Easiest fix in this PR: in the `duplicate_name` subtest, rely on reordering or explicitly pass `--tag` to override the leaked value. Even better, fix the shared `resetAllFlags` helper to also clear the `SliceValue` (e.g. via `f.Value.(pflag.SliceValue).Replace(nil)`) so every subtest starts clean. Verified locally: running just `duplicate_name` passes; running `empty_tag` + `duplicate_name` fails exactly as CI would.

Other notes (non-blocking):
- `internal/validate` has no test file. Since it is now the canonical source of validation used by both API and CLI, a small `internal/validate/template_test.go` covering `NormalizeTags`, `ValidateOptionalVMResourceValue`, and `ValidateTemplateRequest` would lock the shared contract.
- `TestGetLogs_LimitParam` in `internal/api` also fails in this run, but it fails on `main` too — unrelated to this PR.

Please fix the flaky subtest; everything else LGTM.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by chinmay28 — APPROVED** [review]
LGTM. The new `template` CLI commands follow the existing `image.go`/`vm.go` patterns for `newStorageManager`, `paginateSlice`, and `normalizeLimitOffset` — this keeps the commands consistent with the rest of the CLI.

Nice touches:
- Extracting the shared regex/validation into `internal/validate` so CLI and API share the same template validation rules.
- Moving the ID + CreatedAt/UpdatedAt assignment down into `storage.Manager.CreateTemplate` removes the duplicate bookkeeping that would otherwise be needed in both the API handler and the CLI, and the API handler stays green.
- `resetAllFlags` now uses `pflag.SliceValue.Replace(nil)` for slice/array flags, which is the right way to reset repeatable flags between command runs.

Verification I ran locally:
- `go build ./...` — clean.
- `go test ./internal/cli/... -run TestCLI_Template -v` — all 3 new tests pass (create/list/delete, pagination, validation table).
- `go test ./internal/api/... -run Template` — existing API template tests still green after the validation refactor.

Two pre-existing failures I saw during a full `go test ./...` (`TestUploadImage_MissingName` and `TestGetLogs_LimitParam`) also fail on `origin/main` and are unrelated to this PR.

Aligns with ROADMAP 2.4.4 as claimed.

---
_Generated by [Claude Code](https://claude.ai/code)_
