### PR TITLE
feat(daemon): add automatic TLS certificates

### PR DESCRIPTION
**Pull request by march26bot**
## Summary
- add `daemon.tls.auto_cert` config for built-in Let's Encrypt certificate management
- serve HTTPS with `autocert` TLS-ALPN, host allowlisting, cache/email settings, and daemon tests
- document direct `:443` built-in TLS usage in the README, example config, and deployment roadmap

## Testing
- not run locally in this environment (Go toolchain unavailable)

### CODE REVIEW

**Review by chinmay28 — CHANGES_REQUESTED** [review]
Architecture/intent looks right (config plumbing, host allowlist, cache dir, default `auto_cert_cache_dir`, README + roadmap updates), but **the PR does not currently build**. Two concrete blockers found by trying to compile locally on top of `main`:

### 1. Missing `acme` import — compile error

`internal/daemon/daemon.go:62` references `acme.ALPNProto`:

```go
tlsConfig.NextProtos = append([]string{acme.ALPNProto}, tlsConfig.NextProtos...)
```

…but the `acme` package is never imported anywhere in the repo (`grep -rn '"golang.org/x/crypto/acme"' .` returns nothing). `go build ./...` fails with:

```
internal/daemon/daemon.go:62:42: undefined: acme
```

Two ways to fix:

- **Cleanest** — drop the manual `tls.Config` munging and use `autocert.Manager.TLSConfig()` which already wires `GetCertificate`, `acme-tls/1`, and HTTP/2 NextProtos for you:

  ```go
  listenAndServeAutoTLS = func(s *http.Server, mgr *autocert.Manager) error {
      s.TLSConfig = mgr.TLSConfig()
      return s.ListenAndServeTLS("", "")
  }
  ```

  No new import needed; behavior matches the documented `tls-alpn-01` design.

- **Minimal** — add `"golang.org/x/crypto/acme"` to the import block so the existing line compiles.

### 2. `go.sum` not updated for the new `golang.org/x/crypto` dependency

`go.mod` adds `golang.org/x/crypto v0.31.0` but `go.sum` (and the `// indirect` block in `go.mod`) was never regenerated:

```
internal/daemon/daemon.go:24:2: missing go.sum entry for module providing package golang.org/x/crypto/acme/autocert ...
```

After `go mod tidy`, three transitive entries (`golang.org/x/net`, bumped `golang.org/x/sys`, `golang.org/x/text`) plus their hashes are required. Please run `go mod tidy` and commit the result so `make build-go` / CI works.

### Other notes (non-blocking)

- The HTTPS test (`TestServeUsesAutoCertWhenConfigured`) stubs out `listenAndServeAutoTLS`, so it never exercises the real `tls.Config` setup. That's why CI didn't catch the missing `acme` import. If you switch to `mgr.TLSConfig()` per option 1 the test stays valid.
- Consider validating in the daemon (or surfacing a clearer error) when `auto_cert: true` and the listen address isn't `:443` — TLS-ALPN can only succeed on 443, and the README mentions this but nothing enforces it. Minor; happy to defer.

Once the build is green I'm happy to re-review.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by chinmay28 — CHANGES_REQUESTED** [review]
## Review summary

Requesting changes — the daemon does not compile on this branch, so the test suite cannot run.

### Blocker: build failure (`internal/daemon/daemon.go`)

`listenAndServeAutoTLS` references `acme.ALPNProto` (line 62) but only `golang.org/x/crypto/acme/autocert` is imported. The `acme` package is not imported, so:

```
$ go build ./...
internal/daemon/daemon.go:62:42: undefined: acme

$ go test ./internal/daemon/...
internal/daemon/daemon.go:62:42: undefined: acme
FAIL    github.com/vmsmith/vmsmith/internal/daemon [build failed]
```

Fix: add `"golang.org/x/crypto/acme"` to the import block in `internal/daemon/daemon.go` and ensure `go.sum` is regenerated. The PR description explicitly notes Go was unavailable in your environment — please run `go build ./...` and `make test` once that's available before requesting another review.

The `internal/config` tests pass on their own, so the config changes look fine.

### Documentation drift

`CLAUDE.md` (line 357) describes the existing field as:

> `daemon.tls.auto_cert` — public FQDN for automatic Let's Encrypt certificates via Go `autocert`

This PR redefines it as a `bool` and introduces a separate `auto_cert_hosts []string`. CLAUDE.md needs to be updated alongside the README/example config so the codebase guide stays consistent. Worth mentioning the new `auto_cert_hosts`, `auto_cert_cache_dir`, and `auto_cert_email` fields as well.

### Design notes (non-blocking, worth considering)

1. **Listen-port silently ignored.** ACME TLS-ALPN-01 requires the daemon to be reachable on port 443. If a user enables `auto_cert` but leaves `daemon.listen: 0.0.0.0:8080`, certificate issuance will silently fail with confusing logs from autocert. Consider logging a warning at startup if `AutoCertConfigured()` is true but the listen address doesn't end in `:443`.

2. **Cache directory creation.** `autocert.DirCache` lazily creates files but won't `MkdirAll` parents. The README points users at `/var/lib/vmsmith/autocert`, which on a fresh systemd install may not exist with the right ownership. Either create it during daemon startup (alongside `EnsureDirs`) or document the requirement explicitly.

3. **Precedence ordering.** `serve()` evaluates `TLSConfigured()` before `AutoCertConfigured()`, so manual cert files win silently if both are set. That's a reasonable default but worth a one-line note in the README/example so users don't get confused when their `auto_cert: true` setting appears to do nothing.

4. **`acme.AcceptTOS` auto-accept.** Fine for an opt-in flag, but the README should make this explicit so deployers know they're accepting Let's Encrypt's Terms of Service by enabling this.

Once the build is fixed and CLAUDE.md is updated, this should be straightforward to re-review.


---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by chinmay28 — CHANGES_REQUESTED** [review]
Thanks for picking up roadmap item 3.2.3 — the design is on point: TLS-ALPN-01 means we don't need to wrangle a parallel `:80` listener, the host allowlist + cache dir + email config are exactly the surface area expected, the docs/example config update is clear, and adding `AutoCertConfigured()` next to `TLSConfigured()` so manual certs still take precedence is the right call. The unit test that injects `listenAndServeAutoTLS` and asserts the `HostWhitelist` accepts/rejects the right hosts is also a nice touch.

## Blocker — does not compile

`internal/daemon/daemon.go` uses `acme.ALPNProto` inside `listenAndServeAutoTLS`, but the `golang.org/x/crypto/acme` package is never imported. Reproduced locally on this branch:

```
$ CGO_ENABLED=1 go build ./internal/daemon/...
internal/daemon/daemon.go:62:42: undefined: acme
$ CGO_ENABLED=1 go test -count=1 -run NONE ./internal/daemon/
internal/daemon/daemon.go:62:42: undefined: acme
FAIL    github.com/vmsmith/vmsmith/internal/daemon [build failed]
```

Fix is one line — add `"golang.org/x/crypto/acme"` to the import block in `internal/daemon/daemon.go`. Please also run `make test` (or at minimum `go build ./... && go test ./internal/daemon/...`) before re-requesting review; the PR description noting "Go toolchain unavailable" is fine for the review environment, but a build break this direct should ideally be caught by CI before review. If CI didn't flag this, that's worth a follow-up.

## Smaller follow-ups (non-blocking, please address while you're in there)

1. **Validate the listen port when `auto_cert` is enabled.** TLS-ALPN-01 only works when the daemon is reachable on `:443` of the public hostnames. If `daemon.listen` is, say, `:8080` and `auto_cert: true`, the daemon will start, ACME issuance will fail silently on first connection from a real client, and operators get a confusing TLS handshake error. Consider logging a warning at startup (or returning an error from `New()`) when `AutoCertConfigured()` is true and the listen address doesn't end in `:443`.
2. **Cache dir creation.** `autocert.DirCache` creates the directory lazily on first write, but we already have an `EnsureDirs()` pattern. Consider adding `AutoCertCacheDir` to `EnsureDirs()` so a permission error surfaces at startup rather than mid-request when the first cert is requested.
3. **Roadmap note in the PR description.** The description says "not run locally — Go toolchain unavailable." Given how cheap a single `go build` is in CI, please confirm CI is running on this branch — if it isn't, that's the actual gap to close, since this exact bug is what CI would catch.

Once the import is added and CI is green, this is a clean approve.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by chinmay28 — COMMENTED** [review]
This PR has fundamental issues that need resolving before it can be reviewed on its merits.

## The blocker — this PR is in conflict with `main` and reinvents existing functionality

GitHub reports `mergeable_state: dirty` (no CI runs at all), and there's a clear reason:

1. **Autocert was already merged to `main` in #88 (commit `d7046e9`, 2026-04-17)** — almost two weeks before this PR was opened. The shipping implementation lives in `internal/config/config.go:38-50` and `internal/daemon/daemon.go:246-277` on `main` today and uses the shape:
   ```go
   type TLSConfig struct {
     CertFile         string `yaml:"cert_file"`
     KeyFile          string `yaml:"key_file"`
     AutoCert         string `yaml:"auto_cert"`           // single hostname
     AutoCertCacheDir string `yaml:"auto_cert_cache_dir"`
   }
   ```
   This PR re-introduces autocert from scratch as if `main` had nothing — its config diff replaces `cert_file`/`key_file` with the same fields plus four autocert fields, but the rebase hasn't been done so the pre-existing `AutoCert string` / `AutoCertCacheDir` are not accounted for.

2. **The PR head (`28b93bd`) is rooted on `ee62b5d` (#87, 2026-04-16)**, which is _before_ the autocert work landed on `main`. GitHub's PR base pointer says `ffafbae`, but `git log ffafbae..28b93bd` shows only the single autocert commit, which means the PR's branch was never rebased forward. The result is that 60+ files appear in the merge conflict surface, including templates (`internal/cli/template.go`, `internal/api/handlers_template.go`), host stats (`host_stats.go`/`host_stats_test.go`), VM lifecycle events (`internal/vm/events.go`), the VM clone flow, the install script, and ~4000 lines of frontend work. None of these are intentional changes — they're all a side effect of a stale base.

3. **Title alignment issue**: the existing autocert support was already merged for roadmap item 3.2.3, so the roadmap line in this PR's diff (`✅ Done — daemon.tls.auto_cert now enables built-in Let's Encrypt …`) describes work that has shipped. The roadmap on `main` still says "Only practical if daemon has a public FQDN", which is what this PR proposes to update — but the prose change is a rebase artifact, not a real change.

## What the PR actually wants to add (and why it's worth keeping)

Reading just the autocert commit on top of the pre-#88 base, the design improvements over what's on `main` are real and worth landing:

- **Multi-host support** — `AutoCertHosts []string` instead of a single `AutoCert string`. The current main passes `autocert.HostWhitelist(cfg.Daemon.TLS.AutoCert)` with one hostname; multi-domain deployments need a slice.
- **Boolean activation** — separating "do you want autocert?" from "what hosts?" makes the config schema cleaner.
- **`AutoCertEmail`** — ACME contact email for renewal warnings; main currently has no way to set this.
- **Default cache dir under `/var/lib/vmsmith/autocert`** — better than the current `~/.vmsmith/autocert` for systemd-managed deployments where the daemon runs without a home dir.
- **Documentation** — README + example config + roadmap update for direct `:443` usage are all good additions.

## Suggested path forward

Rebase this branch onto current `main`, and reframe the PR as a refactor of the existing `daemon.tls.auto_cert` implementation rather than a from-scratch addition. The actual change scope should then shrink to roughly the four files this work cares about:

1. `internal/config/config.go` — change `AutoCert string` → `AutoCert bool` + add `AutoCertHosts []string` + `AutoCertEmail string`. Update `AutoCertConfigured()` to require both. Note this is a **breaking config change** for any user who already set `auto_cert: vmsmith.example.com` — at minimum, document this in the PR description and ideally accept the old shape as a single-element list for one release.
2. `internal/daemon/daemon.go` — replace `autoCertTLSConfig`'s `HostWhitelist(cfg.Daemon.TLS.AutoCert)` with `HostWhitelist(cfg.Daemon.TLS.AutoCertHosts...)` and set `manager.Email = cfg.Daemon.TLS.AutoCertEmail`. The `serve()` switch is already in place.
3. `internal/config/config_test.go` and `internal/daemon/daemon_test.go` — update / extend the existing autocert tests instead of duplicating them.
4. `README.md`, `vmsmith.yaml.example`, `docs/PRODUCTION_DEPLOYMENT.md`, `docs/ROADMAP.md` — update to match the new shape.

## Minor points (worth carrying through into the rebased PR)

- **`listenAndServeAutoTLS` overrides `s.TLSConfig`** wholesale (`tlsConfig := s.TLSConfig; if tlsConfig == nil { tlsConfig = &tls.Config{} } else { tlsConfig = tlsConfig.Clone() } …`). The existing `autoCertTLSConfig` already builds a complete `tls.Config` (with `MinVersion: tls.VersionTLS12`, h2/http/1.1 next protos, etc.). The PR's override drops that hardening — `MinVersion` would be the Go default (TLS 1.0 prior to Go 1.22, though current Go defaults to 1.2). Worth keeping the `MinVersion: TLS12` floor.
- The PR test (`TestServeUsesAutoCertWhenConfigured`) overrides three function vars (`listenAndServe`, `listenAndServeTLS`, `listenAndServeAutoTLS`). The shape is good, but the existing daemon test on `main` has equivalent coverage already; merging the new fields into that test is preferable to a parallel test.

## Summary

The design ideas are correct and improve over what shipped in #88, but the PR cannot merge as-is — it both conflicts with `main` and would regress unrelated work if force-merged. Please rebase onto current `main`, scope the diff to the autocert refactor only, and call out the breaking config change explicitly.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by chinmay28 — CHANGES_REQUESTED** [review]
## Review summary

Direction is right and aligns with roadmap task 3.2.3, but the PR does not build as-is.

### Blocker — build failure

`internal/daemon/daemon.go:62` references `acme.ALPNProto`, but the `golang.org/x/crypto/acme` package is never imported. Only `golang.org/x/crypto/acme/autocert` is in the import block. Verified locally:

```
$ CGO_ENABLED=1 go build ./...
internal/daemon/daemon.go:62:42: undefined: acme
```

The PR description notes the Go toolchain wasn't available locally, which is why this slipped through. Please add `"golang.org/x/crypto/acme"` to the imports and re-run `go build ./...` and `go test ./...`. Without the fix, `make build` and the daemon tests both fail (`internal/daemon` test package fails to compile, including the new `TestServeUsesAutoCertWhenConfigured`).

### Other observations (non-blocking)

1. **Side-effect on the shared `*http.Server`.** `listenAndServeAutoTLS` mutates `s.TLSConfig` in place. This is fine for the daemon's lifecycle (single call per process) but worth a short comment so a future reader doesn't try to call it twice or share the server.
2. **Operational note.** ACME TLS-ALPN-01 only works on port 443. If the user sets `auto_cert: true` while `daemon.listen` is `:8080`, the daemon will start fine but cert issuance will silently fail at handshake time. Consider either (a) logging a warning when `auto_cert` is on but the listen port isn't 443, or (b) calling that out more prominently in the README/example.
3. **`AutoCertConfigured()` is good** — requiring a non-empty host list before activating mirrors `autocert.HostWhitelist`'s semantics and avoids a cert manager that whitelists nothing.
4. **Tests look solid** — `TestServeUsesAutoCertWhenConfigured` covers the happy path, the host policy allow/deny, and the email + cache fields. Once the import is added these should pass.

Happy to re-approve once the build is green.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by chinmay28 — CHANGES_REQUESTED** [review]
Requesting changes — the branch does not build.

**Blocker 1: undefined `acme.ALPNProto`**

`internal/daemon/daemon.go:62` references `acme.ALPNProto`, but only `golang.org/x/crypto/acme/autocert` is imported (line 24). The `acme` parent package is never imported, so `go build ./...` fails on this branch:

```
internal/daemon/daemon.go:62:undefined: acme
```

Two ways to fix:

1. Add `"golang.org/x/crypto/acme"` to the import block, **or**
2. Drop the hand-rolled TLSConfig and just call `mgr.TLSConfig()` — autocert's `TLSConfig()` already prepends `acme.ALPNProto` to `NextProtos` and wires `GetCertificate`, which is exactly what this code is reproducing. That removes the `crypto/tls` import and the manual config cloning entirely:

```go
listenAndServeAutoTLS = func(s *http.Server, mgr *autocert.Manager) error {
    s.TLSConfig = mgr.TLSConfig()
    return s.ListenAndServeTLS("", "")
}
```

Option 2 is the documented usage pattern in the autocert package.

**Blocker 2: `go.sum` is incomplete for the new dependency**

`go.mod` adds `golang.org/x/crypto v0.31.0` but `go.sum` only has the `go.mod` hash, not the module hash. Building fails with:

```
missing go.sum entry for module providing package golang.org/x/crypto/acme/autocert
```

Run `CGO_ENABLED=1 go mod tidy` and commit the updated `go.sum`. (The same is likely true for transitive deps such as `golang.org/x/net` that autocert pulls in.)

**Other notes (non-blocking, please consider)**

- The PR's test plan checkbox for `make test` is unchecked because the toolchain wasn't available locally. Please run `CGO_ENABLED=1 go test -race -count=1 ./...` once the build is fixed and confirm `TestServeUsesAutoCertWhenConfigured` passes.
- TLS-ALPN-01 only works when the daemon actually owns `:443`. The README snippet implies this but it would be worth a one-line callout that an HTTP-01 fallback (port 80) is **not** wired in — issuance fails silently for hosts that aren't reachable on `:443/tcp` from Let's Encrypt.
- `DefaultConfig()` sets `AutoCertCacheDir` to `filepath.Join(dataDir, "autocert")`, but the README/example documents the hardcoded `/var/lib/vmsmith/autocert`. They drift if `dataDir` is overridden via XDG. Consider documenting that the example value is the default for the standard install path only.

Once the build/sum issues are fixed and the existing daemon tests pass with `go test`, the design otherwise lines up cleanly with roadmap item 3.2.3 — config schema, host whitelist, cache dir, contact email, and a unit test that asserts the manager is wired with the right policy. Happy to re-review.

---
_Generated by [Claude Code](https://claude.ai/code)_
